### ISSUE TITLE
adding daemon option to openconfigbeat

### ISSUE THREAD

**Issue by PaoloSupino** [aristanetworks/openconfigbeat#5]
The beats: filebeat, metricbeat and packetbeat (the ones I checked, there might be other) include a binary wrapper called [beat name]-god in the directory /usr/share/[beat name]/bin. This is a wrapper to the beat that is launched at system startup. 

Please add this feature to openconfigbeat.

**Comment by 7AC** [comment]
I looked at the code in https://github.com/elastic/beats/tree/master/dev-tools/packer and looks like it assumes that the beat lives in the `elastic/beats` repo (the target is `make package`). Under the hood I think it's just using [tsg/go-daemon](https://github.com/tsg/go-daemon), so my suggestion is to create the daemon file yourself doing the same. We'd like to keep this repo platform-independent so I wouldn't add logic for this sort of stuff at this point.

**Comment by 7AC** [comment]
The `make package` is now working as of https://github.com/aristanetworks/openconfigbeat/commit/b870b33a1603124256d9a4e7a278e46b7f81cdb2, it could help your use case
